import subprocess
from datetime import datetime
from pathlib import Path
import requests
import os


def ensure_clean_working_tree(repo_path: str):
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=repo_path,
        capture_output=True,
        text=True
    )

    if result.stdout.strip():
        raise RuntimeError("Repository has uncommitted changes. Reset first.")


def create_branch_only(repo_path: str) -> str:
    ensure_clean_working_tree(repo_path)

    branch_name = f"fix-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    subprocess.run(
        ["git", "checkout", "-b", branch_name],
        cwd=repo_path,
        check=True
    )

    return branch_name


def commit_changes(repo_path: str, file_path: str):
    repo_path = Path(repo_path)
    file_path = Path(file_path)

    relative_path = file_path.relative_to(repo_path)

    subprocess.run(
        ["git", "add", str(relative_path)],
        cwd=repo_path,
        check=True
    )

    subprocess.run(
        ["git", "commit", "-m", "AI automated code fix"],
        cwd=repo_path,
        check=True
    )


def push_branch(repo_path: str, branch_name: str):
    subprocess.run(
        ["git", "push", "-u", "origin", branch_name],
        cwd=repo_path,
        check=True
    )


def create_pull_request(repo_url: str, branch_name: str) -> str:
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN missing")

    repo_url = repo_url.replace(".git", "")
    parts = repo_url.split("/")
    owner = parts[-2]
    repo = parts[-1]

    api_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json"
    }

    data = {
        "title": "AI Automated Code Fix",
        "head": branch_name,
        "base": "main",
        "body": "This PR was automatically generated by AI Coding Standards Enforcer."
    }

    response = requests.post(api_url, headers=headers, json=data)

    if response.status_code != 201:
        raise RuntimeError(response.text)

    return response.json()["html_url"]