from app.agent.schemas.spec import Spec


def generate_file_content(path: str, spec: Spec) -> str:
    if path.endswith("main.py"):
        return f'''"""
Main entry point for {spec.project_name}
"""

from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    return {{"message": "Hello from {spec.project_name}"}}
'''

    if path.endswith("test_health.py"):
        return '''def test_dummy():
    assert True
'''

    if path.endswith("README.md"):
        return f"# {spec.project_name}\n\nGenerated by CodeGen Agent."

    if path.endswith("pyproject.toml"):
        return "[project]\nname = \"generated\"\nversion = \"0.1.0\""

    return ""