# app/services/git_service.py

import subprocess
from datetime import datetime

import requests


def create_branch_only(repo_path: str) -> str:
    branch_name = f"fix-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    subprocess.run(["git", "fetch"], cwd=repo_path, check=True)
    subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_path, check=True)

    return branch_name


def commit_changes(repo_path: str):
    subprocess.run(["git", "add", "."], cwd=repo_path, check=True)

    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"],
        cwd=repo_path,
        capture_output=True,
        text=True,
    )

    if not result.stdout.strip():
        print("No changes to commit.")
        return

    subprocess.run(
        ["git", "commit", "-m", "AI automated code fixes"],
        cwd=repo_path,
        check=True,
    )


def push_branch(repo_path: str, branch_name: str, github_token: str, repo_url: str):
    clean_url = repo_url.replace("https://", "")
    authenticated_url = f"https://x-access-token:{github_token}@{clean_url}"

    subprocess.run(
        ["git", "push", "-u", authenticated_url, branch_name],
        cwd=repo_path,
        check=True,
    )


def create_pull_request(repo_url: str, branch_name: str, github_token: str):
    repo_url = repo_url.replace(".git", "")
    parts = repo_url.split("/")
    owner = parts[-2]
    repo = parts[-1]

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
    }

    repo_api_url = f"https://api.github.com/repos/{owner}/{repo}"
    repo_response = requests.get(repo_api_url, headers=headers)

    default_branch = repo_response.json()["default_branch"]

    pulls_api_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"

    data = {
        "title": "AI Automated Code Fix",
        "head": branch_name,
        "base": default_branch,
        "body": "This PR was automatically generated by AI Coding Standards Enforcer.",
    }

    response = requests.post(pulls_api_url, headers=headers, json=data)

    if response.status_code != 201:
        raise RuntimeError(response.text)

    return response.json()["html_url"]
